{"errorMessage": "ATLAS_URI environment variable is required", "errorType": "ValueError", "requestId": "716ff86f-34f1-42e5-a659-eb4643546345", "stackTrace": ["  File \"/var/task/learning_path_generator.py\", line 539, in lambda_handler\n    generator = get_generator()\n", "  File \"/var/task/learning_path_generator.py\", line 534, in get_generator\n    generator_instance = LearningPathGenerator()\n", "  File \"/var/task/learning_path_generator.py\", line 68, in __init__\n    self.mongo_client = get_mongo_client()\n", "  File \"/var/task/utils/mongodb_client.py\", line 166, in get_mongo_client\n    _mongo_client = MongoDBClient()\n", "  File \"/var/task/utils/mongodb_client.py\", line 19, in __init__\n    raise ValueError(\"ATLAS_URI environment variable is required\")\n"]}